[package]
name = "opaque_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "opaque_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["extension-module"] }
regex = "1"
